language: c++
compiler: g++
os: windows

script:
  - make
  - ./main
  - cd bin
  - ./maintest
  - git ls-files src/ | xargs clang-format -i && git diff --exit-code
  - git ls-files test/ | xargs clang-format -i && git diff --exit-code