language: c++
compiler: g++
os: windows

script:
  - make
  - make test
  - cd bin
  - ./maintest.exe
  - git ls-files src/ | xargs clang-format -i && git diff --exit-code
  - git ls-files test/ | xargs clang-format -i && git diff --exit-code